destinations:
  "192.168.4.4:9000":
    upstream: "http://localhost:3000"
    tenants:
      "staging":
        mode: "allowlist" # denylist
        groups:
          - name: "group1"
          - name: "group2"